### ISSUE TITLE
How to get "name" attribute

### ISSUE THREAD

**Issue by eusonlito** [oscarotero/form-manager#41]
Before version 4.3, I could get the name attribute using `$input->attr('name')` because `name` is a tag attribute, but now returns null.

There are a new method to get the input name?

**Comment by oscarotero** [comment]
Yes. The reason is because the name depends of the position of the input in the form tree and some attributes as "multiple". For example:
```php
$form = F::form()->add([
    'color' => F::select() //The name should be "color"
]);

$form = F::form()->add([
    'preferences' => F::group([
        'color' => F::select() //The name should be "preferences[color]"
    ])
]);
$form['preferences']['color']->multiple(true); //now, the name should be "preferences[color][]"
```
So, the final name is calculated just before strigify the input. You can see the code here: https://github.com/oscarotero/form-manager/blob/master/src/Traits/InputTrait.php#L80

If you need to know the input name for whatever reason, as you can see in the code, `$input->getPath()` returns the full path of the input and empty brackets "[]" are appended for multiple values.

**Comment by eusonlito** [comment]
But name is an attribute as `class`  or `required`  or `type`. I don't know why can I get required and not name. I'm using abstract form processing into laravel and I don't know input names. Here a code example:

```php
if ($input->attr('type') !== 'file') {
    continue;
}

$name = $input->attr('name');

if ($file = Input::file($name)) {
    $data[$name] = self::saveFile($file, $folder.'/'.$name);
}
```

Thanks.

**Comment by oscarotero** [comment]
Because `name` is a special attribute that affects the data structure and it cannot be modified. But I see your point and I can make this value more accessible. What about make this attribute read-only?, for example:

```php
$select = F::select();
echo $select->attr('name'); //Returns null

$form['colors'] = $select;
echo $select->attr('name'); //Returns "colors"

$select->multiple();
echo $select->attr('name'); //Returns "colors[]"

$select->attr('name', 'colours'); //throws an exception: The 'name' attribute is read-only
```

**Comment by eusonlito** [comment]
:+1:
