### ISSUE TITLE
Prepending Hidden field to Checkboxes

### ISSUE THREAD

**Issue by Patabugen** [oscarotero/form-manager#50]
It's common practice to create a hidden field before a checkbox so the browser presents a value even if the checkbox is not ticked (rather than not submitting the field).

So the output for a checkbox would be:

```
<input type='hidden' name='someName' value='off'>
<input type='checkbox' name='someName' value='on'>
```

I think it would be good for FormManager to do this, or at least have an option on the checkbox to enable it - but I'm not sure it can have two fields of the same name added?

I'm happy to implement and send a PR if you could give me some guidance on how to implement it.

**Comment by oscarotero** [comment]
Hi.
Yes, I did things like this before form-manager and it's useful if you want to get an array with all fields defined, even empy fields. But with form-manager it's not necesary because it returns the values of all fields, including the empy ones.

If you want to receive a value always for a specific field, maybe checkbox is not the better choice, because it's a boolean input. Maybe a input type radio is better:

```html
<input type='radio' name='someName' value='on'> Yes
<input type='radio' name='someName' value='off'> No
```
Anyway, if you want a hidden input on every checkboxes, the best way is use the render:

```php
$form['someName'] = F::checkbox()->render(function ($input) {
    return '<input type="hidden" name="' . $input->attr('name') .'" value="off">' . $input;
});
```

**Comment by Patabugen** [comment]
Ahh right you are!
