### ISSUE TITLE
Radio buttons lose their name attr

### ISSUE THREAD

**Issue by rkrater** [oscarotero/form-manager#61]
When I add a radio button to a choose group the radio buttons lose their name attr.

**Example**

```php
echo  $Program_Name = F::radio()->id("rdoProgramName")->name('rdoProgramName')->label('Program Name');
<input type="radio" id="rdoProgramName" name="rdoProgramName" aria-labelledby="fm-1"> <label id="fm-1" for="rdoProgramName">Program Name</label> 
```
```php
$Program_Name = F::radio()->id("rdoProgramName")->name('rdoProgramName')->label('Program Name');
$pif_type = F::choose()->add([$Program_Name]);

<div><input type="radio" id="rdoProgramName" value="0" aria-labelledby="fm-1"> <label id="fm-1" for="rdoProgramName">Program Name</label> </div>
```

**Comment by oscarotero** [comment]
Hi, thanks for reporting.
FYI, this library should be used in this way:

```php
$form = F::form([
    'colors' => F::choose([
        'red' => F::radio()->label('Red'),
        'blue' => F::radio()->label('Blue'),
    ])
]);
```
As you can see, `radio` is inside the `choose` using the values as keys (red, blue), and `choose` is inside the `form` using the name `colors`, so the name of the all radios is "colors", because is the key used by the choose. As you can see, this library is intended to build a data structure, and the names of the fields change accordingly. Building independent fields without a root can generate undesired behaviours.

Anyway, I've fixed this to do not modify the name when the field has not a parent (which is this case).

**Comment by oscarotero** [comment]
New version released with this fix
